import './globals.css'
import { StyledEngineProvider, CssBaseline } from '@/components/mui-material';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <StyledEngineProvider injectFirst>
      <CssBaseline />
      <html lang="en">
        <body>{children}</body>
      </html>
    </StyledEngineProvider>
  )
}
